### ISSUE TITLE
install server from source

### ISSUE THREAD

**Issue by vijay543** [dkmstr/openuds#10]
Hi Team,

I am trying to build the server from source ....can you please point me to appropriate documentaion for the same. 

Thanks,
T Vijay.

**Comment by dkmstr** [comment]
Hi vijay543,
Unfortunately, that is the currently "lack" for the project, we do not have a full documentation describing how to build it.
Although we know that some people have already built it from github source, we have not such documents.

We currently are looking for help on this area, so everybody should benefit from it.

Best regards,

**Comment by vijay543** [comment]
Hi ,

I am able to get the broker up, but am not able to configure any services from dashboard.
For now i am thinking the client browser is missing the plugin , which is preventing me from doing this.

Also i try to download the plugin but i get a error.
Please confirm. Also any small  help in building the plugins would be much appreciated.
Thanks,
T Vijay.

**Comment by dkmstr** [comment]
Hi,

You should not have any problems adding services to the dashboard with UDS even if you don't have the plugin or the actors. The UDS plugin is for accesing the VMs, but you can also access them using HTML5 so no client plugin is needed.
You will need the actor, inside the VM, because is the element that UDS uses to comunicate and give instructions to services.

maybe now its easier to use the Guacamole connector. You can build it from "guacamole-tunnel" (there is a pom.xml there to build it).
Also, take into Account that "master" version is very unstable, i recommend you to use the 2.1 stable version branch, or the 2.2 testing version branch.

For compiled client versions, the simplest way to get them are requesting a free version of uds from https://www.udsenterprise.com, the virtual appliance will have all of them.

You can compile client plugin & actors from the source, that is located on openuds/client & openuds/actor.
The Linux builders are included (under "linux", but the windows one are not, because they are built on a "manual" way.

Hope this helps you,
For any question, you can contact me again ;-)

Best Regards,

Adolfo Gómez

**Comment by ahmedkaballo** [comment]
HI Adolfo Gómez,
how can i build the server ?
what is the main directory or file to build or start the server?
thanks in advance.

**Comment by dkmstr** [comment]
Yhe server do not need to be built.
This is a django based app. I recomendy you to start looking at the server/src folder (use 2.2 version or 2.1, not master that is completly unstable), and familarieze with django,
There are also dependencies that need to be built, that are in the folder "server/requirements.txt" (if you found something missing, please, let us know).

**Comment by ahmedkaballo** [comment]
Thanks for your reply
i couldn't find "settings.py"  but i found settings.py.sample and when i renamed it to settings.py  and run python manage.py sync it gives me the following error
 Traceback (most recent call last):
  File "manage.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 347, in execute
    django.setup()
  File "/usr/local/lib/python3.5/dist-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/usr/local/lib/python3.5/dist-packages/django/utils/log.py", line 73, in configure_logging
    logging_config_func(logging_settings)
  File "/usr/lib/python3.5/logging/config.py", line 795, in dictConfig
    dictConfigClass(config).configure()
  File "/usr/lib/python3.5/logging/config.py", line 566, in configure
    '%r: %s' % (name, e))
ValueError: Unable to configure handler 'authFile': [Errno 2] No such file or directory: '/home/kaballo/openuds/server/src/log/auth.log'

**Comment by ahmedkaballo** [comment]
Hi Adolfo Gómez.
can i use the versions of packages in the "requirements" file in master branch for openuds 2.2 ?
because requirements file for openuds 2.2 doesn't include versions of packages.
