### ISSUE TITLE
building plugin for client.

### ISSUE THREAD

**Issue by vijay543** [dkmstr/openuds#11]
Hi ,

I am able to get the broker up, but am not able to configure any services from dashboard.
For now i am thinking the client browser is missing the plugin , which is preventing me from doing this.

Also i try to download the plugin but i get a error.
Please confirm. Also any small help in building the plugins would be much appreciated.

Thanks,
T Vijay.

**Comment by dkmstr** [comment]
Hi,

You should not have any problems adding services to the dashboard with 
UDS even if you don't have the plugin or the actors. The UDS plugin is 
for accesing the VMs, but you can also access them using HTML5 so no 
client plugin is needed.
You will need the actor, inside the VM, because is the element that UDS 
uses to comunicate and give instructions to services.

maybe now its easier to use the Guacamole connector. You can build it 
from "guacamole-tunnel" (there is a pom.xml there to build it).
Also, take into Account that "master" version is very unstable, i 
recommend you to use the 2.1 stable version branch, or the 2.2 testing 
version branch.

For compiled client versions, the simplest way to get them are 
requesting a free version of uds from https://www.udsenterprise.com, the 
virtual appliance will have all of them.

You can compile client plugin & actors from the source, that is located 
on openuds/client & openuds/actor.
The Linux builders are included (under "linux", but the windows one are 
not, because they are built on a "manual" way.

Hope this helps you,
For any question, you can contact me again ;-)

Best Regards,

Adolfo Gómez

**Comment by vijay543** [comment]
Thanks Adolfo Gomez , i will try with 2.1 Stable version. Btw in the "master " version, the root password are hardcoded(root/udsmam0). Is this different from admin password.

Also when i login with root password i am not able to do any user management(create or delete users).
Is there any specific way to create and configure admin password.

Thanks,
T Vijay.

**Comment by dkmstr** [comment]
Hi, this is the "default" root password, go to dashboard once you enter, to tools, configuration, and there you can change the "root" username, the password, or even "disallow" it to enter UDS.
BTW, the "root" password can not have assigned services, is an special "superuser". To have an user with services, create an authenticator ;-)

The manual of the free version i told you before (there is one) is fully applicable to the OpenSource one, and maybe a goot place to start with admin. 

again, go to https://www.udsenterprise.com and request a free version. You will get all you need, and that will help you a lot to build this up from scratch.

**Comment by ahmedkaballo** [comment]
Hi
i want to know if the open source version of UDS(Open UDS) supports multiple hypervisors or not!
Thanks in advance.

**Comment by dkmstr** [comment]
Of course yes!!!
Take a look at what is included:
https://github.com/dkmstr/openuds/tree/master/server/src/uds/services
Ovirt, Openstack, OpenNebula, OpenGnsys (on beta currently), Xen Server, and you can include your own also!!! ;-)

Best regards

**Comment by ahmedkaballo** [comment]
Thanks for replying very soon Adolfo Gomez.
actually we are working on a VDI project and we want it to be open source and with a raspberry pi as a thin client .
we tried plenty of the open source solutions  but we couldn't find any solution that fits well with raspberry pi except Citrix and it's commercial so it won't be suitable.
 my question is , do you know any open source solution that we could use with raspberry pi?
and thanks for your help...

**Comment by vijay543** [comment]
Thanks Adolfo Gomez, I have built the guacamole.war(transport.war from target folder) from pom.xml and placed it in /var/lib/tomcat6/webapps/ but it seems it does not come up.....

Please let me know if i am missing any thing....

btwn, I tried apache guacamole...it seems to work.
