### ISSUE TITLE
does openuds support ovirt version4.2 

### ISSUE THREAD

**Issue by vijay543** [dkmstr/openuds#15]
Hi Team,

When we are trying to publish services, it indefinitely hangs  with out any response
Ovirt version: 4.2.

This was working fine with Ovirt version 4.0.
Wanted to check if there is support for this Ovirt version.

Thanks,
T Vijay

**Comment by dkmstr** [comment]
I'll check it. It's confirmed to work on 4.1 correctly, but has no data with 4.2.
¿Wich brach of uds do you use?

**Comment by dkmstr** [comment]
After testing, UDS 2.2 supports correctly oVirt 4.2 (we have installed a testing environment and works correctly).
UDS 2.1 does not support oVirt 4.2, because there is a field removed on 4.2 API call and fails.
So, you have to use UDS 2.2, and be sure to have ovirt-engine-sdk-python tu latest version (because if don't, 4.2 will neither work).

Hope this helps you

**Comment by ahmedkaballo** [comment]
Hello vijay543 
We're trying to install openuds with ovirt but the openuds lacks documentaion
can you help us ?
at least tell us how to install.
