### ISSUE TITLE
Waiting for removal

### ISSUE THREAD

**Issue by karthik-msys** [dkmstr/openuds#16]
Hi Team,
when we are deleted service pool status displays as  **waiting for removal** is not deleting completely from ui.

Thanks,
A.karthik

**Comment by dkmstr** [comment]
Normally this is because "the backend" is not running. (Maybe it's dead?)
Ensure you have "python manage.py taskManager --stop --start" (the --stop is to test that if it is already running, stop it, and the start for starting it).
Also, please, take a look at the logs file, probably there will be something that will help you.

**Comment by karthik-msys** [comment]
Which log file i need to test.actually uds and services log file is not showing anything
