### ISSUE TITLE
Restrained services pools

### ISSUE THREAD

**Issue by karthik-msys** [dkmstr/openuds#17]
Hi Team,
What is the meaning of **Restrained services pools** in Dashboard.

**Comment by dkmstr** [comment]
This means that the service is getting too many errors, and the service pool is being "slowed down".
If a pool has N user services in error in the last X minutes, the serice pool gets restrained, and no new service pools get created until this rule is not met. By default the values are 3 errors in 10 minutes. You can change it on configuration, from dashboard. After changing it, you need to restart UDS frontend & bakend, because this values are cached.

Hope this helps
