### ISSUE TITLE
Service pool delete is not working

### ISSUE THREAD

**Issue by anji-msys** [dkmstr/openuds#18]
Hi Team,
- Created service pools and then click on delete service pool.
- Pool status has changed to **Waiting for removal** but service is not removed from the service pool list even waited for couple of minutes.
- We used Openuds v2.2.

**Comment by anji-msys** [comment]
Hi Team,

-  Created service pools and then click on delete service pool.
-  Pool status has changed to Waiting for removal but keep on try to delete service for at-least 5 time.
- The Service pool grid size is keep on decreases for each delete operation. Please find attachment for info.
![screen1](https://user-images.githubusercontent.com/36300286/36029852-e683a39e-0dca-11e8-9565-4172e8cae2be.png)
![scren1](https://user-images.githubusercontent.com/36300286/36029803-b32ac8c4-0dca-11e8-95bd-da1f0e0278e1.png)

**Comment by dkmstr** [comment]
Yeap, that is the way it work... :-)
UDS Has 2 main components, the frontend (the web you see), and the backend (that is the responsible of doing most operations...)
In order to work with UDS, you should also run the "backend". To do this, try "python manage.py taskManager --stop --start" from the openuds/server/src folder.
Remember also to use an stable version, or at least the beta one, because the "master" is the alpha, and currently is moving fast.
So use 2.2 with django 1.11, that should work fine.

Hope this helps
