### ISSUE TITLE
Why UDS Plugin's location can be empty?

### ISSUE THREAD

**Issue by teterkin** [dkmstr/openuds#22]
Hi!
Why UDS Plugin's location can be empty? 
/static/clients/
Do we need to build the clients? How can we do that?

**Comment by dkmstr** [comment]
Hi,
Efectively, you have to build your own.
On /client (on this repository) it's what is needed to build the linux clients.
Unfortunately, windows client is a bit more difficult to build, i we have not fully automated yet, so you will have to use the source code directly (with python), or build it by your own, or download the one from the free version that is already compiled.

Anyway, remember that master version is not functional, its a "work in progress", and now more than ever because we are migrating the user interface, the backend from 2.7 to 3.5, etc...

Hope this helps,

Best Regards,

**Comment by teterkin** [comment]
Thank you!
