### ISSUE TITLE
Steps for installation openuds

### ISSUE THREAD

**Issue by harigist** [dkmstr/openuds#27]
Hi @dkmstr 

Could you provide the steps to install OpenUDS? I find it very difficult to install this openuds, Please provide it.

Thanks,
Hari

**Comment by dkmstr** [comment]
Hi,
There is already an "very simple" installation guide, it's outdated but may guide you in some way.
https://github.com/dkmstr/openuds/blob/master/server/documentation/intro/install.rst

Also, do not try to install "master", because right now is under heavy development, and will probably not work for you. Use the 2.2/2.1 braches, that are fully functional.

**Comment by harigist** [comment]
Hi @dkmstr 

Thanks for pointing this, I initially tried this and it seems very tuff and I get many python dependency error, Could you provide the simple script which install all these packages ? 

It would be a Great help for us.

Thanks,
Harry
