### ISSUE TITLE
FreeRDP command line change affects linux UDSClient

### ISSUE THREAD

**Issue by danitorregrosa** [dkmstr/openuds#54]
FreeRDP has deprecated CHANNEL_TSMF and [has modified](https://github.com/FreeRDP/FreeRDP/commit/829497b313b2e8e5fc809c71466eb5a4db1a44dd) its command line for multimedia redirection from "/multimedia:..." to "/video".

When UDSClient launches FreeRDP with multimedia redirection and there is installed a new FreeRDP version compiled without CHANNEL_TSMF_CLIENT flag (e.g. in current Arch Linux package), FreeRDP is not launched (it prints command line help instead).

So, there will be some versions of FreeRDP that use "/multimedia:..." (older ones) and other versions (newer ones) that will not be launched with this "/multimedia:..." parameter and need "/video" instead.

**Comment by dkmstr** [comment]
Thanks for the report.
We have updated on 2.2 and master (3.0) branches, so now UDS will use /video instead of /multimedia.
For old clients, the best is to upgrade frerdp client to at least a 2.0 version, and if not possible, provide a customized transport without the "multimedia" flag, and add "/multimedia:...." as a custom parameter
